version: 0.2
phases:
  install:
    commands:  
      - npm install
  build:
    commands:
      - npm run-script build
      - npm run cdk synth -- -o cf
artifacts:
  base-directory: cf
  files: '**/*'      
        
    