version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 8  
    commands:  
      - npm install
  build:
    commands:
      - npm run-script build
      - npm run cdk synth -- -o cf
artifacts:
  base-directory: cf
  files: '**/*'
    